name: Build and Release AUR Package

on:
  workflow_dispatch:
    inputs:
      aur_repo_url:
        description: 'URL of the AUR package repository'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Arch Linux
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git

      - name: Create a non-root user
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          mkdir -p /home/builder/aur-package
          chown -R builder:builder /home/builder/aur-package

      - name: Clone AUR package repository
        run: |
          sudo -u builder git clone ${{ github.event.inputs.aur_repo_url }} /home/builder/aur-package

      - name: Build the AUR package
        run: |
          cd /home/builder/aur-package
          sudo -u builder makepkg -si --noconfirm

      - name: Upload release assets
        uses: actions/upload-artifact@v2
        with:
          name: aur-package
          path: /home/builder/aur-package/*.pkg.tar.zst

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download built package
        uses: actions/download-artifact@v2
        with:
          name: aur-package
          path: ./release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/*.pkg.tar.zst
          name: Aur build
          body: none
          tag_name: ${{github.run_id}}
