name: Build and Release AUR Package

on:
  workflow_dispatch:
    inputs:
      aur_repo_url:
        description: 'URL of the AUR package repository'
        required: true
        default: 'https://aur.archlinux.org/floorp-bin.git'
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB.TOKEN}}
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io containerd
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Run Arch Linux container and build package
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/aur 
          docker run --name arch-linux  archlinux:latest /bin/bash -c "
          sed -i '/\[multilib\]/,/Include/s/^#//' /etc/pacman.conf && pacman -Syu --noconfirm &&
          pacman -S git base-devel sudo imagemagick optipng --noconfirm &&
          useradd -m builduser &&
           echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            su - builduser -c '
              git clone ${{ github.event.inputs.aur_repo_url }} /home/builduser/aur-package/ &&
              ls /home/builduser/aur-package/ &&
              cd /home/builduser/aur-package &&
              makepkg -f --noconfirm
            '
            "
            docker start arch-linux
            docker cp arch-linux:/home/builduser/aur-package/ ${GITHUB_WORKSPACE}/aur/
            ls aur/aur-package/

      - name: Check if Recovery Exist
        run: |
          cd ${GITHUB_WORKSPACE}/aur
          if [ -f  aur-package/*.zst ]; then
            echo "CHECK_PKG_IS_OK=true" >> $GITHUB_ENV
          else
            echo "PKG directory is empty."
          fi
                  
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: env.CHECK_PKG_IS_OK == 'true'
        with:
          files: aur/aur-package/*.zst
          name: Aur package
          tag_name: ${{github.run_id}}
          body: Aur packges
