name: Build and Release AUR Package

on:
  workflow_dispatch:
    inputs:
      aur_name:
        description: 'Exact name of the AUR package nothing extra'
        required: true
        default: 'r-quick-share'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest 
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB.TOKEN}}
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Arch Linux container and build package
        run: |
          set -e 
          pacman -Syu --noconfirm &&
          pacman -S git base-devel sudo curl wget openh264 --needed --noconfirm &&
          useradd -m builduser &&
          echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
          su - builduser
          sudo chown -R builduser:builduser /home/builduser
          cd /home/builduser
          sudo -u builduser git clone https://aur.archlinux.org/yay.git
          cd yay
          sudo -u builduser makepkg -si --noconfirm 
          sudo -u builduser yay -S --noconfirm  ${{github.event.inputs.aur_name}} 
          cd /home/builduser
          mv .cache/*/${{ github.event.inputs.aur_name }}*.zst ./ 
      - name: Check if Pkgs Exist
        run: |
          cd /home/builduser  
          if ls  "${{github.event.inputs.aur_name}}"*.zst 1> /dev/null 2>&1; then
            echo "CHECK_PKG_IS_OK=true" >> $GITHUB_ENV &&
            echo "Found them"
          else
            echo "PKG directory is empty."
          fi
                  
      - name: Upload to Release
        if: env.CHECK_PKG_IS_OK == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: /home/builduser/${{github.event.inputs.aur_name}}*.zst
          name: Aur package ${{ github.event.inputs.aur_name }}
          tag_name: ${{github.run_id}}
          body: Aur packges ${{ github.event.inputs.aur_name }}
