name: Build and Release AUR Package

on:
  workflow_dispatch:
    inputs:
      aur_name:
        description: 'name of the AUR package '
        required: true
        default: 'floorp-bin '
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB.TOKEN}}
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io containerd
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Run Arch Linux container and build package
        run: |
          docker run --name arch-linux  archlinux:latest /bin/bash -c "
          pacman -Syu --noconfirm &&
          pacman -S git base-devel sudo --needed --noconfirm &&
          useradd -m builduser &&
           echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            su - builduser -c '
          git clone https://aur.archlinux.org/paru.git && cd paru && makepkg -si --noconfirm &&
              paru -S --noconfirm ${{ github.event.inputs.aur_name }} 
            '
            "
            docker start arch-linux
            docker cp arch-linux:/home/builduser/.cache/paru ~ 
           ls -la  

      - name: Check if Pkgs Exist
        run: |
          cd ~ && cp */*.zst ./  
          if [ -f  ./*.zst ]; then
            echo "CHECK_PKG_IS_OK=true" >> $GITHUB_ENV &&
            echo "Found them"
          else
            echo "PKG directory is empty."
          fi
                  
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.zst
          name: Aur package ${{ github.event.inputs.aur_name }}
          tag_name: ${{github.run_id}}
          body: Aur packges
