name: Build and Release AUR Package

on:
  workflow_dispatch:
    inputs:
      aur_repo_url:
        description: 'URL of the AUR package repository'
        required: true
        default: 'https://aur.archlinux.org/floorp-bin.git'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --name arch-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Arch Linux
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git

      - name: Create non-root user
        run: |
          useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /home/builduser/aur-package
          chown -R builduser:builduser /home/builduser/aur-package

      - name: Clone AUR package repository
        run: |
          sudo -u builduser git clone ${{ github.event.inputs.aur_repo_url }} /home/builduser/aur-package

      - name: Build the package
        run: |
          cd /home/builduser/aur-package
          sudo -u builduser makepkg -si --noconfirm
          docker cp arch-linux:/home/builduser/aur-package/*.pkg.tar.zst ${GITHUB_WORKSPACE}/

  release:

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/*.pkg.tar.zst
          asset_name: aur-package.pkg.tar.zst
          asset_content_type: application/x-tar
